from __future__ import annotations

from pydantic import BaseModel, Field

from crewai_factory.tasks import EditorVerdict


class Attempt(BaseModel):
    """Structured attempt made by the writer agent."""

    cycle: int = Field(description="The cycle number of this attempt.")
    score: int = Field(ge=0, le=100, description="Quality score from 0 to 100.")
    content: str = Field(description="The post content generated by the writer.")
    feedback: str = Field(description="Feedback from the editor for this attempt.")


class ContentState(BaseModel):
    """Shared state for the content-generation flow, updated in place by each step."""

    topic: str = Field(default="", description="The topic generated by the strategist.")
    post: str = Field(default="", description="The post written by the writer.")
    verdict: EditorVerdict | None = Field(
        default=None, description="The verdict returned by the editor."
    )
    max_attempts: int = Field(
        default=3, description="The maximum number of attempts allowed for the writer."
    )
    attempts: list[Attempt] = Field(
        default_factory=list, description="A list of all attempts made by the writer."
    )
